# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ImageField(upload_to='quiz/img')),
                ('answer', models.TextField()),
                ('name', models.CharField(default='your name', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('disappear', models.BooleanField(default=False)),
                ('again', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=80)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
